## This is playbbook where role is defined
---
- hosts: localhost
  remote_user: root
  become: true
  collections:
    - amazon.aws
  roles: 
    - aws_vpc
  vars_files:
    - aws_vpc/defaults/main.yml
  
